def exception(a, b):
    """
    Exception - це навчальна функція, яка демонструє роботу з винятками в Python.

    Використовуючи обробку винятків, функція запитує введення двох значень. Якщо хоча
    б одне з них не є числом, виконується конкатенація. В інших випадках введені
    числа підсумовуються.

    :param a:  для перевірки необхідно ввести не число (зпрацює except)
    :param b:  для перевірки необхідно ввести не число (зпрацює except)
    :return:  s

    """

    try:
        a_ = int(a)
        b_ = int(b)
        s = a_+b_
        print("сума чисел: ", s)

    except (ValueError, TypeError):  # або залишити except Exception

        s = a + b
        print(f'конкатенація: {s}')

    finally:
        print()
        print("Дякуємо за увагу!")

    return s


if __name__ == "__main__":
    a = input('Введіть число А: ')
    b = input('Введіть число N: ')
    exception(a, b)
